Federated identity support
Azure/kubelogin pull request #81
Opened 2022-03-29 19:41 UTC by tesharp

Add support for using federated workload identity

```bash
kubelogin get-token --login workloadidentity --server-id 6dae42f8-4368-4678-94ff-3960e28e3643
```

Works out of the box with the new azure-workload-identity (pod-identity v2) service in AKS. Our use case is making ArgoCD authenticate to other clusters with a federated identity instead of providing it with username / password.

2022-03-31 22:56 UTC, weinong commented on README.md
> +Workload identity uses [Azure AD federated identity credentials](https://docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredentials-overview?view=graph-rest-beta) to authenticate to AK
after reading the code, i understand the usage now. so its just a file containing signed token to be federated with AAD

2022-03-31 23:24 UTC, weinong commented on pkg/converter/convert.go
>  	// MSI and AzureCLI login bypass most login fields, so we'll check for them and exclude them
```suggestion
	// MSI, AzureCLI, and WorkloadIdentity login bypass most login fields, so we'll check for them and exclude them
```

2022-03-31 23:30 UTC, weinong commented on pkg/token/federatedIdentity.go
> +		ExpiresOn:   json.Number(fmt.Sprintf("%v", result.ExpiresOn.UTC().Unix())),
```suggestion
		ExpiresOn:   json.Number(fmt.Sprintf("%d", result.ExpiresOn.UTC().Unix())),
```

2022-04-01 03:56 UTC, weinong commented on README.md
> +Workload identity uses [Azure AD federated identity credentials](https://docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredentials-overview?view=graph-rest-beta) to authenticate to AK
```suggestion
Workload identity uses [Azure AD federated identity credentials](https://docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredentials-overview?view=graph-rest-beta) to authenticate to Kubernetes clusters with AAD integration. This works by setting the environment variables:
* `AZURE_CLIENT_ID`, Azure Active Directory application ID that is federated with workload identity
* `AZURE_TENANT_ID`, Azure Active Directory tenant ID
* `AZURE_FEDERATED_TOKEN_FILE`, which has client assertion of workload identity (e.g. jwt)
* `AZURE_AUTHORITY_HOST`, the host of the Azure Active Directory authority
```

2022-04-01 03:57 UTC, weinong commented on pkg/token/federatedIdentity.go
> +		return emptyToken, fmt.Errorf("failed to read service account token: %s", err)
```suggestion
		return emptyToken, fmt.Errorf("failed to read client assertion from token file: %s", err)
```

2022-04-01 04:01 UTC, weinong commented on pkg/token/federatedIdentity.go
> +	if resourceID == "" {
i think we should rename `resourceID` to `serverID` as that's what is being used in the input.

2022-04-01 04:05 UTC, weinong requested changes
some minor changes. but looks awesome!

2022-04-01 04:08 UTC, weinong commented on pkg/token/federatedIdentity.go
> +	return adal.Token{
please also set the ResourceID like https://github.com/Azure/kubelogin/pull/82/files#diff-a8ce026dded66e441e7429e429180634d4cc8c48bce447956a32bde36862b238R61

2022-04-01 07:58 UTC, tesharp commented
Thanks, have fixed suggested changes :)

2022-04-01 07:59 UTC, tesharp commented on README.md
> +Workload identity uses [Azure AD federated identity credentials](https://docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredentials-overview?view=graph-rest-beta) to authenticate to AK
do you want some more description on this? I added the suggestion you made in another comment

2022-04-02 01:54 UTC, weinong approved these changes
awesome!

2022-04-02 01:55 UTC, weinong commented
@tesharp, out of curiosity, what is your scenario to use workload identity?

2022-04-02 02:20 UTC, merged

2022-04-03 18:20 UTC, weinong commented
https://github.com/weinong/azure-federated-identity-samples

2022-04-03 19:33 UTC, tesharp commented
Thats awesome and perfect use case for it :)

In my case Im using it to authenticate to multiple clusters from ArgoCD. Basically all infra is deployed with terraform and all AKS clusters are private with Azure AD RBAC enabled. Using this method I can deploy all required resources and grant access in Azure, without passing any secrets to ArgoCD but just granting the service account it uses priviledges in the AKS cluster to manage.

2022-11-24 14:54 UTC, AlexisDuf commented
@tesharp I will interested to see how looks like the cluster configuration to use azure workload identity. 

Are you using proxy-sidecar ? 

I tried this configuration for my authenticated to my cluster but it's not working 
```
      name: mycluster
      labels:
        env: dev
      server: https://aks-api.com:443
      config:
        execProviderConfig:
          command: "kubelogin"
          apiVersion: "client.authentication.k8s.io/v1beta1"
          args: ["get-token", "--server-id", "6dae42f8-4368-4678-94ff-3960e28e3630", "--login", "workloadidentity"]
        tlsClientConfig:
          insecure: true
```

2022-11-28 20:11 UTC, tesharp commented
Hi @AlexisDuf . That is exactly how I do it, only with setting all the certificates required in `tlsClientConfig` section. That has been working without problems since I made this PR

2023-09-15 13:18 UTC, adam-harries commented
@tesharp are you able to share the code samples where you configure external AKS clusters in Argo CD via Workload Identity? I've scoured the web and can't find any complete examples of how to achieve this :(